name: 'Android Builder'
on:  push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: javavirys/android:${{ secrets.ANDROID_BUILD_TOOLS }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        docker-build-args: "--build-arg android_compile_sdk=${{ secrets.ANDROID_COMPILE_SDK }} --build-arg android_build_tools=${{ secrets.ANDROID_BUILD_TOOLS }} --build-arg android_command_line_tools=${{ secrets.ANDROID_SDK_TOOLS }}"
